targets:
  $default:
    builders:
      juicer|juice_generator:
        enabled: true

builders:
  juicer:
    target: 'juicer'
    import: 'package:juicer/generator.dart'
    builder_factories: ['juiceGenerator']
    build_extensions: {'.dart': ['.juicer.dart']}
    auto_apply: dependents
    build_to: source
    applies_builders: ['source_gen']
