name: juicer
version: 0.10.0+3
description: Lightweight JSON serialization library for plain, mutable classes
homepage: https://github.com/skawa-universe/juicer

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ">=0.32.4 <1.0.0"
  build: ">=1.0.0 <2.0.0"
  source_gen: ">=0.9.0 <0.10.0"

dev_dependencies:
  test: any
  build_test: any
  build_runner: any
  build_web_compilers: any
  pedantic: ^1.0.0
